// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Photo struct {
	ID           string     `json:"id"`
	TripID       string     `json:"trip_id"`
	StopID       *string    `json:"stop_id"`
	Filename     string     `json:"filename"`
	OriginalName string     `json:"original_name"`
	Caption      string     `json:"caption"`
	Lat          *float64   `json:"lat"`
	Lng          *float64   `json:"lng"`
	TakenAt      *time.Time `json:"taken_at"`
	Width        int64      `json:"width"`
	Height       int64      `json:"height"`
	SizeBytes    int64      `json:"size_bytes"`
	CreatedAt    time.Time  `json:"created_at"`
	CamHeading   *float64   `json:"cam_heading"`
	CamPitch     *float64   `json:"cam_pitch"`
	CamRange     *float64   `json:"cam_range"`
}

type Route struct {
	ID        string    `json:"id"`
	TripID    string    `json:"trip_id"`
	Name      string    `json:"name"`
	Geojson   string    `json:"geojson"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
}

type Stop struct {
	ID           string     `json:"id"`
	TripID       string     `json:"trip_id"`
	Title        string     `json:"title"`
	Description  string     `json:"description"`
	Lat          float64    `json:"lat"`
	Lng          float64    `json:"lng"`
	Elevation    float64    `json:"elevation"`
	StopOrder    int64      `json:"stop_order"`
	ArrivedAt    *time.Time `json:"arrived_at"`
	CreatedAt    time.Time  `json:"created_at"`
	LocationName string     `json:"location_name"`
}

type Trip struct {
	ID                string    `json:"id"`
	ShareID           string    `json:"share_id"`
	Title             string    `json:"title"`
	Description       string    `json:"description"`
	CoverPhotoID      *string   `json:"cover_photo_id"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	DefaultCamHeading *float64  `json:"default_cam_heading"`
	DefaultCamPitch   *float64  `json:"default_cam_pitch"`
	DefaultCamRange   *float64  `json:"default_cam_range"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
