// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trips.sql

package dbgen

import (
	"context"
	"time"
)

const claimOrphanedTrips = `-- name: ClaimOrphanedTrips :exec
UPDATE trips SET user_id = ? WHERE user_id IS NULL
`

func (q *Queries) ClaimOrphanedTrips(ctx context.Context, userID *string) error {
	_, err := q.db.ExecContext(ctx, claimOrphanedTrips, userID)
	return err
}

const clearPhotoStopIDs = `-- name: ClearPhotoStopIDs :exec
UPDATE photos SET stop_id = NULL WHERE trip_id = ?
`

func (q *Queries) ClearPhotoStopIDs(ctx context.Context, tripID string) error {
	_, err := q.db.ExecContext(ctx, clearPhotoStopIDs, tripID)
	return err
}

const countPhotos = `-- name: CountPhotos :one
SELECT COUNT(*) FROM photos WHERE trip_id = ?
`

func (q *Queries) CountPhotos(ctx context.Context, tripID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPhotos, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStops = `-- name: CountStops :one
SELECT COUNT(*) FROM stops WHERE trip_id = ?
`

func (q *Queries) CountStops(ctx context.Context, tripID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStops, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :exec
INSERT INTO comments (id, photo_id, trip_id, author, body, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateCommentParams struct {
	ID        string    `json:"id"`
	PhotoID   string    `json:"photo_id"`
	TripID    string    `json:"trip_id"`
	Author    string    `json:"author"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.ID,
		arg.PhotoID,
		arg.TripID,
		arg.Author,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const createPhoto = `-- name: CreatePhoto :exec
INSERT INTO photos (id, trip_id, stop_id, filename, original_name, caption, lat, lng, taken_at, width, height, size_bytes, created_at, is_video)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePhotoParams struct {
	ID           string     `json:"id"`
	TripID       string     `json:"trip_id"`
	StopID       *string    `json:"stop_id"`
	Filename     string     `json:"filename"`
	OriginalName string     `json:"original_name"`
	Caption      string     `json:"caption"`
	Lat          *float64   `json:"lat"`
	Lng          *float64   `json:"lng"`
	TakenAt      *time.Time `json:"taken_at"`
	Width        int64      `json:"width"`
	Height       int64      `json:"height"`
	SizeBytes    int64      `json:"size_bytes"`
	CreatedAt    time.Time  `json:"created_at"`
	IsVideo      int64      `json:"is_video"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) error {
	_, err := q.db.ExecContext(ctx, createPhoto,
		arg.ID,
		arg.TripID,
		arg.StopID,
		arg.Filename,
		arg.OriginalName,
		arg.Caption,
		arg.Lat,
		arg.Lng,
		arg.TakenAt,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.CreatedAt,
		arg.IsVideo,
	)
	return err
}

const createRoute = `-- name: CreateRoute :exec
INSERT INTO routes (id, trip_id, name, geojson, color, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateRouteParams struct {
	ID        string    `json:"id"`
	TripID    string    `json:"trip_id"`
	Name      string    `json:"name"`
	Geojson   string    `json:"geojson"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) error {
	_, err := q.db.ExecContext(ctx, createRoute,
		arg.ID,
		arg.TripID,
		arg.Name,
		arg.Geojson,
		arg.Color,
		arg.CreatedAt,
	)
	return err
}

const createStop = `-- name: CreateStop :exec
INSERT INTO stops (id, trip_id, title, description, lat, lng, elevation, stop_order, arrived_at, created_at, location_name)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateStopParams struct {
	ID           string     `json:"id"`
	TripID       string     `json:"trip_id"`
	Title        string     `json:"title"`
	Description  string     `json:"description"`
	Lat          float64    `json:"lat"`
	Lng          float64    `json:"lng"`
	Elevation    float64    `json:"elevation"`
	StopOrder    int64      `json:"stop_order"`
	ArrivedAt    *time.Time `json:"arrived_at"`
	CreatedAt    time.Time  `json:"created_at"`
	LocationName string     `json:"location_name"`
}

func (q *Queries) CreateStop(ctx context.Context, arg CreateStopParams) error {
	_, err := q.db.ExecContext(ctx, createStop,
		arg.ID,
		arg.TripID,
		arg.Title,
		arg.Description,
		arg.Lat,
		arg.Lng,
		arg.Elevation,
		arg.StopOrder,
		arg.ArrivedAt,
		arg.CreatedAt,
		arg.LocationName,
	)
	return err
}

const createTrip = `-- name: CreateTrip :exec
INSERT INTO trips (id, share_id, title, description, created_at, updated_at, user_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateTripParams struct {
	ID          string    `json:"id"`
	ShareID     string    `json:"share_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	UserID      *string   `json:"user_id"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) error {
	_, err := q.db.ExecContext(ctx, createTrip,
		arg.ID,
		arg.ShareID,
		arg.Title,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const deletePhoto = `-- name: DeletePhoto :exec
DELETE FROM photos WHERE id = ?
`

func (q *Queries) DeletePhoto(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePhoto, id)
	return err
}

const deletePhotosByTrip = `-- name: DeletePhotosByTrip :exec
DELETE FROM photos WHERE trip_id = ?
`

func (q *Queries) DeletePhotosByTrip(ctx context.Context, tripID string) error {
	_, err := q.db.ExecContext(ctx, deletePhotosByTrip, tripID)
	return err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes WHERE id = ?
`

func (q *Queries) DeleteRoute(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRoute, id)
	return err
}

const deleteRoutesByTrip = `-- name: DeleteRoutesByTrip :exec
DELETE FROM routes WHERE trip_id = ?
`

func (q *Queries) DeleteRoutesByTrip(ctx context.Context, tripID string) error {
	_, err := q.db.ExecContext(ctx, deleteRoutesByTrip, tripID)
	return err
}

const deleteStop = `-- name: DeleteStop :exec
DELETE FROM stops WHERE id = ?
`

func (q *Queries) DeleteStop(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteStop, id)
	return err
}

const deleteStopsByTrip = `-- name: DeleteStopsByTrip :exec
DELETE FROM stops WHERE trip_id = ?
`

func (q *Queries) DeleteStopsByTrip(ctx context.Context, tripID string) error {
	_, err := q.db.ExecContext(ctx, deleteStopsByTrip, tripID)
	return err
}

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM trips WHERE id = ?
`

func (q *Queries) DeleteTrip(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTrip, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, photo_id, trip_id, author, body, created_at FROM comments WHERE id = ?
`

func (q *Queries) GetComment(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.TripID,
		&i.Author,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, trip_id, stop_id, filename, original_name, caption, lat, lng, taken_at, width, height, size_bytes, created_at, cam_heading, cam_pitch, cam_range, is_video, photo_order FROM photos WHERE id = ?
`

func (q *Queries) GetPhoto(ctx context.Context, id string) (Photo, error) {
	row := q.db.QueryRowContext(ctx, getPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.StopID,
		&i.Filename,
		&i.OriginalName,
		&i.Caption,
		&i.Lat,
		&i.Lng,
		&i.TakenAt,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.CamHeading,
		&i.CamPitch,
		&i.CamRange,
		&i.IsVideo,
		&i.PhotoOrder,
	)
	return i, err
}

const getStop = `-- name: GetStop :one
SELECT id, trip_id, title, description, lat, lng, elevation, stop_order, arrived_at, created_at, location_name, cam_lng, cam_lat, cam_height, cam_heading, cam_pitch FROM stops WHERE id = ?
`

func (q *Queries) GetStop(ctx context.Context, id string) (Stop, error) {
	row := q.db.QueryRowContext(ctx, getStop, id)
	var i Stop
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Title,
		&i.Description,
		&i.Lat,
		&i.Lng,
		&i.Elevation,
		&i.StopOrder,
		&i.ArrivedAt,
		&i.CreatedAt,
		&i.LocationName,
		&i.CamLng,
		&i.CamLat,
		&i.CamHeight,
		&i.CamHeading,
		&i.CamPitch,
	)
	return i, err
}

const getTrip = `-- name: GetTrip :one
SELECT id, share_id, title, description, cover_photo_id, created_at, updated_at, default_cam_heading, default_cam_pitch, default_cam_range, present_slug, user_id FROM trips WHERE id = ?
`

func (q *Queries) GetTrip(ctx context.Context, id string) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTrip, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.ShareID,
		&i.Title,
		&i.Description,
		&i.CoverPhotoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultCamHeading,
		&i.DefaultCamPitch,
		&i.DefaultCamRange,
		&i.PresentSlug,
		&i.UserID,
	)
	return i, err
}

const getTripByPresentSlug = `-- name: GetTripByPresentSlug :one
SELECT id, share_id, title, description, cover_photo_id, created_at, updated_at, default_cam_heading, default_cam_pitch, default_cam_range, present_slug, user_id FROM trips WHERE present_slug = ?
`

func (q *Queries) GetTripByPresentSlug(ctx context.Context, presentSlug *string) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTripByPresentSlug, presentSlug)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.ShareID,
		&i.Title,
		&i.Description,
		&i.CoverPhotoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultCamHeading,
		&i.DefaultCamPitch,
		&i.DefaultCamRange,
		&i.PresentSlug,
		&i.UserID,
	)
	return i, err
}

const getTripByShareID = `-- name: GetTripByShareID :one
SELECT id, share_id, title, description, cover_photo_id, created_at, updated_at, default_cam_heading, default_cam_pitch, default_cam_range, present_slug, user_id FROM trips WHERE share_id = ?
`

func (q *Queries) GetTripByShareID(ctx context.Context, shareID string) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTripByShareID, shareID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.ShareID,
		&i.Title,
		&i.Description,
		&i.CoverPhotoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultCamHeading,
		&i.DefaultCamPitch,
		&i.DefaultCamRange,
		&i.PresentSlug,
		&i.UserID,
	)
	return i, err
}

const listCommentsByPhoto = `-- name: ListCommentsByPhoto :many
SELECT id, photo_id, trip_id, author, body, created_at FROM comments WHERE photo_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByPhoto(ctx context.Context, photoID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByPhoto, photoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PhotoID,
			&i.TripID,
			&i.Author,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByTrip = `-- name: ListCommentsByTrip :many
SELECT id, photo_id, trip_id, author, body, created_at FROM comments WHERE trip_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByTrip(ctx context.Context, tripID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PhotoID,
			&i.TripID,
			&i.Author,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotos = `-- name: ListPhotos :many
SELECT id, trip_id, stop_id, filename, original_name, caption, lat, lng, taken_at, width, height, size_bytes, created_at, cam_heading, cam_pitch, cam_range, is_video, photo_order FROM photos WHERE trip_id = ? ORDER BY photo_order ASC, created_at ASC
`

func (q *Queries) ListPhotos(ctx context.Context, tripID string) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, listPhotos, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.StopID,
			&i.Filename,
			&i.OriginalName,
			&i.Caption,
			&i.Lat,
			&i.Lng,
			&i.TakenAt,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.CamHeading,
			&i.CamPitch,
			&i.CamRange,
			&i.IsVideo,
			&i.PhotoOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosByStop = `-- name: ListPhotosByStop :many
SELECT id, trip_id, stop_id, filename, original_name, caption, lat, lng, taken_at, width, height, size_bytes, created_at, cam_heading, cam_pitch, cam_range, is_video, photo_order FROM photos WHERE stop_id = ? ORDER BY photo_order ASC, created_at ASC
`

func (q *Queries) ListPhotosByStop(ctx context.Context, stopID *string) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, listPhotosByStop, stopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.StopID,
			&i.Filename,
			&i.OriginalName,
			&i.Caption,
			&i.Lat,
			&i.Lng,
			&i.TakenAt,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.CamHeading,
			&i.CamPitch,
			&i.CamRange,
			&i.IsVideo,
			&i.PhotoOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosWithLocation = `-- name: ListPhotosWithLocation :many
SELECT id, trip_id, stop_id, filename, original_name, caption, lat, lng, taken_at, width, height, size_bytes, created_at, cam_heading, cam_pitch, cam_range, is_video, photo_order FROM photos WHERE trip_id = ? AND lat IS NOT NULL AND lng IS NOT NULL ORDER BY taken_at ASC, created_at ASC
`

func (q *Queries) ListPhotosWithLocation(ctx context.Context, tripID string) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, listPhotosWithLocation, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.StopID,
			&i.Filename,
			&i.OriginalName,
			&i.Caption,
			&i.Lat,
			&i.Lng,
			&i.TakenAt,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.CamHeading,
			&i.CamPitch,
			&i.CamRange,
			&i.IsVideo,
			&i.PhotoOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, trip_id, name, geojson, color, created_at FROM routes WHERE trip_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListRoutes(ctx context.Context, tripID string) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoutes, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Name,
			&i.Geojson,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStops = `-- name: ListStops :many
SELECT id, trip_id, title, description, lat, lng, elevation, stop_order, arrived_at, created_at, location_name, cam_lng, cam_lat, cam_height, cam_heading, cam_pitch FROM stops WHERE trip_id = ? ORDER BY stop_order ASC
`

func (q *Queries) ListStops(ctx context.Context, tripID string) ([]Stop, error) {
	rows, err := q.db.QueryContext(ctx, listStops, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stop{}
	for rows.Next() {
		var i Stop
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Title,
			&i.Description,
			&i.Lat,
			&i.Lng,
			&i.Elevation,
			&i.StopOrder,
			&i.ArrivedAt,
			&i.CreatedAt,
			&i.LocationName,
			&i.CamLng,
			&i.CamLat,
			&i.CamHeight,
			&i.CamHeading,
			&i.CamPitch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrips = `-- name: ListTrips :many
SELECT id, share_id, title, description, cover_photo_id, created_at, updated_at, default_cam_heading, default_cam_pitch, default_cam_range, present_slug, user_id FROM trips ORDER BY updated_at DESC
`

func (q *Queries) ListTrips(ctx context.Context) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, listTrips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.ShareID,
			&i.Title,
			&i.Description,
			&i.CoverPhotoID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultCamHeading,
			&i.DefaultCamPitch,
			&i.DefaultCamRange,
			&i.PresentSlug,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByUser = `-- name: ListTripsByUser :many
SELECT id, share_id, title, description, cover_photo_id, created_at, updated_at, default_cam_heading, default_cam_pitch, default_cam_range, present_slug, user_id FROM trips WHERE user_id = ? ORDER BY updated_at DESC
`

func (q *Queries) ListTripsByUser(ctx context.Context, userID *string) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, listTripsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.ShareID,
			&i.Title,
			&i.Description,
			&i.CoverPhotoID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultCamHeading,
			&i.DefaultCamPitch,
			&i.DefaultCamRange,
			&i.PresentSlug,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxStopOrder = `-- name: MaxStopOrder :one
SELECT COALESCE(MAX(stop_order), -1) FROM stops WHERE trip_id = ?
`

func (q *Queries) MaxStopOrder(ctx context.Context, tripID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxStopOrder, tripID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const resetTripDefaults = `-- name: ResetTripDefaults :exec
UPDATE trips SET cover_photo_id = NULL, default_cam_heading = NULL, default_cam_pitch = NULL, default_cam_range = NULL, updated_at = ? WHERE id = ?
`

type ResetTripDefaultsParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) ResetTripDefaults(ctx context.Context, arg ResetTripDefaultsParams) error {
	_, err := q.db.ExecContext(ctx, resetTripDefaults, arg.UpdatedAt, arg.ID)
	return err
}

const setPhotoStopAndOrder = `-- name: SetPhotoStopAndOrder :exec
UPDATE photos SET stop_id = ?, photo_order = ? WHERE id = ?
`

type SetPhotoStopAndOrderParams struct {
	StopID     *string `json:"stop_id"`
	PhotoOrder int64   `json:"photo_order"`
	ID         string  `json:"id"`
}

func (q *Queries) SetPhotoStopAndOrder(ctx context.Context, arg SetPhotoStopAndOrderParams) error {
	_, err := q.db.ExecContext(ctx, setPhotoStopAndOrder, arg.StopID, arg.PhotoOrder, arg.ID)
	return err
}

const setPhotoStopID = `-- name: SetPhotoStopID :exec
UPDATE photos SET stop_id = ? WHERE id = ?
`

type SetPhotoStopIDParams struct {
	StopID *string `json:"stop_id"`
	ID     string  `json:"id"`
}

func (q *Queries) SetPhotoStopID(ctx context.Context, arg SetPhotoStopIDParams) error {
	_, err := q.db.ExecContext(ctx, setPhotoStopID, arg.StopID, arg.ID)
	return err
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments SET author = ?, body = ? WHERE id = ?
`

type UpdateCommentParams struct {
	Author string `json:"author"`
	Body   string `json:"body"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment, arg.Author, arg.Body, arg.ID)
	return err
}

const updatePhoto = `-- name: UpdatePhoto :exec
UPDATE photos SET stop_id = ?, caption = ?, lat = ?, lng = ?, cam_heading = ?, cam_pitch = ?, cam_range = ? WHERE id = ?
`

type UpdatePhotoParams struct {
	StopID     *string  `json:"stop_id"`
	Caption    string   `json:"caption"`
	Lat        *float64 `json:"lat"`
	Lng        *float64 `json:"lng"`
	CamHeading *float64 `json:"cam_heading"`
	CamPitch   *float64 `json:"cam_pitch"`
	CamRange   *float64 `json:"cam_range"`
	ID         string   `json:"id"`
}

func (q *Queries) UpdatePhoto(ctx context.Context, arg UpdatePhotoParams) error {
	_, err := q.db.ExecContext(ctx, updatePhoto,
		arg.StopID,
		arg.Caption,
		arg.Lat,
		arg.Lng,
		arg.CamHeading,
		arg.CamPitch,
		arg.CamRange,
		arg.ID,
	)
	return err
}

const updatePhotoOrder = `-- name: UpdatePhotoOrder :exec
UPDATE photos SET photo_order = ? WHERE id = ?
`

type UpdatePhotoOrderParams struct {
	PhotoOrder int64  `json:"photo_order"`
	ID         string `json:"id"`
}

func (q *Queries) UpdatePhotoOrder(ctx context.Context, arg UpdatePhotoOrderParams) error {
	_, err := q.db.ExecContext(ctx, updatePhotoOrder, arg.PhotoOrder, arg.ID)
	return err
}

const updatePresentSlug = `-- name: UpdatePresentSlug :exec
UPDATE trips SET present_slug = ?, updated_at = ? WHERE id = ?
`

type UpdatePresentSlugParams struct {
	PresentSlug *string   `json:"present_slug"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          string    `json:"id"`
}

func (q *Queries) UpdatePresentSlug(ctx context.Context, arg UpdatePresentSlugParams) error {
	_, err := q.db.ExecContext(ctx, updatePresentSlug, arg.PresentSlug, arg.UpdatedAt, arg.ID)
	return err
}

const updateStop = `-- name: UpdateStop :exec
UPDATE stops SET title = ?, description = ?, lat = ?, lng = ?, elevation = ?, stop_order = ?, arrived_at = ?, location_name = ?, cam_lng = ?, cam_lat = ?, cam_height = ?, cam_heading = ?, cam_pitch = ? WHERE id = ?
`

type UpdateStopParams struct {
	Title        string     `json:"title"`
	Description  string     `json:"description"`
	Lat          float64    `json:"lat"`
	Lng          float64    `json:"lng"`
	Elevation    float64    `json:"elevation"`
	StopOrder    int64      `json:"stop_order"`
	ArrivedAt    *time.Time `json:"arrived_at"`
	LocationName string     `json:"location_name"`
	CamLng       *float64   `json:"cam_lng"`
	CamLat       *float64   `json:"cam_lat"`
	CamHeight    *float64   `json:"cam_height"`
	CamHeading   *float64   `json:"cam_heading"`
	CamPitch     *float64   `json:"cam_pitch"`
	ID           string     `json:"id"`
}

func (q *Queries) UpdateStop(ctx context.Context, arg UpdateStopParams) error {
	_, err := q.db.ExecContext(ctx, updateStop,
		arg.Title,
		arg.Description,
		arg.Lat,
		arg.Lng,
		arg.Elevation,
		arg.StopOrder,
		arg.ArrivedAt,
		arg.LocationName,
		arg.CamLng,
		arg.CamLat,
		arg.CamHeight,
		arg.CamHeading,
		arg.CamPitch,
		arg.ID,
	)
	return err
}

const updateTrip = `-- name: UpdateTrip :exec
UPDATE trips SET title = ?, description = ?, cover_photo_id = ?, default_cam_heading = ?, default_cam_pitch = ?, default_cam_range = ?, updated_at = ? WHERE id = ?
`

type UpdateTripParams struct {
	Title             string    `json:"title"`
	Description       string    `json:"description"`
	CoverPhotoID      *string   `json:"cover_photo_id"`
	DefaultCamHeading *float64  `json:"default_cam_heading"`
	DefaultCamPitch   *float64  `json:"default_cam_pitch"`
	DefaultCamRange   *float64  `json:"default_cam_range"`
	UpdatedAt         time.Time `json:"updated_at"`
	ID                string    `json:"id"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) error {
	_, err := q.db.ExecContext(ctx, updateTrip,
		arg.Title,
		arg.Description,
		arg.CoverPhotoID,
		arg.DefaultCamHeading,
		arg.DefaultCamPitch,
		arg.DefaultCamRange,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
